[WIP] Update Debit Generation Queries For SIP09 Compatibility
Storj/billing pull request #87
Opened 2017-10-23 21:55 UTC by pgerbes1

2017-10-26 16:44 UTC, dylanlott commented
@pgerbes1 looks good to me, is this ready to go then?

2017-10-26 18:02 UTC, pgerbes1 commented
@dylanlott Cool, thanks for taking a look. There is still some testing to be done so I'll move it back to WIP for now.

2018-02-22 23:10 UTC, dylanlott commented
@pgerbes1 any update on this? Are we waiting on anything or should we take this to staging for more testing?

2018-02-22 23:24 UTC, braydonf commented
I think waiting for https://github.com/Storj/bridge/pull/521 to be merged, and related.

2018-05-24 23:57 UTC, jtolio requested changes
halting sip9 work

2018-10-29 18:48 UTC, RichardLitt commented
Closing as stale. Thank you.

2018-10-29 18:48 UTC, closed without merging